### PR TITLE
Port from GObject to GLib

### PR DESCRIPTION
**Pull request by JuiP**
Tested; Please review and merge @quozl

### CODE REVIEW

**Comment by chimosky** [comment]
Tested, works as expected.

Also I feel your commit message in 880de7d can be improved.

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [x] keep the associated text and use https://web.archive.org/web/20130310093700/http://lovesexandthermonuclearwar.wordpress.com/2012/04/04/assorted-chess-tools/ rather than delete the link.

**Comment by JuiP** [comment]
Sure! Added the link back :)

**Comment by quozl** [comment]
Thanks.

**Pull request merged**
